[app]
GOOGLE_API_KEY = "AlzaSyChZVofa_SevT4el27Dyvc7kBwpW1FkRds"
MONGODB_URI = "mongodb+srv://DanielQuispeCcorahua:elefante123@dqcc.yqviwyh.mongodb.net/"
USER = "DanielQuispeCcorahua"
COHERE_API_KEY = "BEnVGoaTTOp1TfYQyc3uDViXFudBDvLR8yv7Dwrf"

[b2]
B2_BUCKET_NAME = "DALQCC"
B2_READ_KEY_ID = "0054ba8306c47c20000000005"
B2_READ_APPLICATION_KEY = "AK-LECTURA-DQCC"
B2_WRITE_KEY_ID = "0054ba8306c47c20000000006"
B2_WRITE_APPLICATION_KEY = "AK-ESCRITURA-DQCC"

